### ISSUE TITLE
HTTP::Server::PSGI crash when header value is utf8 string

### ISSUE THREAD

**Issue by vlet** [plack/Plack#353]
$ plackup -E deployment -s HTTP::Server::PSGI -e 'sub {[200,[x=>"\x{100}"],[""]]}' &

$ curl http://127.0.0.1:5000/
Wide character in syswrite at /usr/lib64/perl5/IO/Handle.pm line 478.
curl: (52) Empty reply from server
[1]  + exit 255   plackup -E deployment -s Standalone -e 'sub {[200,[x=>"\x{100}"],[""]]}'

**Comment by miyagawa** [comment]
Yep, fixed by #429
