### ISSUE TITLE
Provide hook in Plack::Loader::Restarter to run callback before restart? 

### ISSUE THREAD

**Issue by genehack** [plack/Plack#504]
It would be sometimes useful if `Plack::Loader::Restarter` could run arbitrary code (i.e., run a provided callback) during the restart cycle in `_fork_and_start()`. (One use case for this is a static site generator that wants to monitor input files and regenerate output files.)

I have implemented code to do this, but it is very tightly coupled to Plack internals and I am not too happy with it. See https://github.com/genehack/HiD/commit/c42dd5dfb3c8e852466d603fc8560732d468a43c#diff-8126999ec0b26e6c455cbae4a91ba51bR1, where i had to make a Handler class just to have a place to hang the method I wanted to call, and a Loader class to pass in the object I need to be able to reference in the Handler.

This would be a lot cleaner if I could pass in a callback to Restarter that closed over the object. I could have done that by subclassing Restarter and overriding `run`, but it would have been 99% copy and paste and it just felt worse to do that than what I ended up doing. 

How would you feel about a patch that added the ability to set a callback method that would be called in `_fork_and_start` if it existed?

**Comment by miyagawa** [comment]
Sounds sensible!

**Comment by genehack** [comment]
Hopefully that is an acceptable way to go about setting up the callback -- somewhat tricky since Loaders don't seem to be designed to take any sort of arguments, really.
