### ISSUE TITLE
t/Plack-Middleware/wrapcgi.t Fails when Perl is not Main Perl

### ISSUE THREAD

**Issue by theory** [plack/Plack#509]
I'm building a Perl that goes into /usr/local/perl520. This test fails because the script that gets run, `t/Plack-Middleware/cgi-bin/cgi_dir.cgi`, starts with this line:

    #!/usr/bin/env perl

And then dies when it can't find CGI, which is not included with the system Perl. I think this script should be run with the same perl as the test are running under.

**Comment by miyagawa** [comment]
Actually fixed it so that it won't use CGI.pm.

**Comment by theory** [comment]
Well that seems sensible. :-)

**Comment by exodist** [comment]
theoretically this can still be broken by the assumption there is a system perl at all :-)   not suggesting you actually act on that though.
