### ISSUE TITLE
Multiple GET parameters with the same name in Plack::Request

### ISSUE THREAD

**Issue by sni** [plack/Plack#510]
Hi,

When i have an URI like: ...?a=1&a=2 i would expect Plack::Request::query_parameters to contain both values. Instead the result is:
```
$VAR1 = bless( {
                 'a' => '2'
               }, 'Hash::MultiValue' );
```
I probably would expect something like:
```
$VAR1 = bless( {
                 'a' => ['1', '2']
               }, 'Hash::MultiValue' );
```

**Comment by sni** [comment]
ok, i found out that i can do a
```
$c->req->parameters->get_all('a')
```
but this looks a bit counter-intuitive to me, especcially since Data::Dumper can't handle this.

**Comment by sni** [comment]
ok, never mind. Hash::MultiValue has a ->mixed function which does exactly what i need. Sry for the noise :-)

**Comment by miyagawa** [comment]
They're documented in Plack::Request [documentation](https://metacpan.org/pod/Plack::Request#Hash::MultiValue-parameters)
