### ISSUE TITLE
Plack::App::File spam log file

### ISSUE THREAD

**Issue by KES777** [plack/Plack#516]
the examle of logged string:

Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Plack/App/File.pm line 30.
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Plack/App/File.pm line 30.

**Comment by miyagawa** [comment]
Same as the other issue on the debug panel. Your PSGI environment variables are incomplete. Use Lint middleware to detect such misconfiguration during the development and testing.

**Comment by KES777** [comment]
I know, that is not right place, but you can save ton time and nerves for developers if you drom line to logthat:

`warn 'You have to set SCRIPT_NAME environment variable in PSGI. Consult uwsgi doc for how to set it.'   unless SCRIPT_NAME`

*seems this is same. answer only to one thread. thankyou.

**Comment by miyagawa** [comment]
No, you must use Lint middleware to validate PSGI environment. Doing so in every piece of PSGI apps to ensure the environment is correct is a waste of resource, both in coding and runtime.

**Comment by KES777** [comment]
I agree with you, but people's time is much expensive VS hardware resources.
`unless SCRIPT_NAME || production`

**Comment by KES777** [comment]
Thank you for your answers. I stop discussion.
