### ISSUE TITLE
Implement option to route Log::Any messages into log4perl

### ISSUE THREAD

**Issue by KES777** [plack/Plack#527]
In my code 
```
use Log::Any::Adapter;
Log::Any::Adapter->set('Log4perl');

builder {
   ....
   enable 'Log4perl';
```

It will be good to have option to route all messages from Log::Any to Log4perl

    enable 'Log4perl', route_from => 'Log::Any';

**Comment by miyagawa** [comment]
I assume your original code already works this way, adding bunch of options to make the configuration code shorter isn't my interest. In general, middleware should do as little/thin as possible so that users can configure as you like, just like you did.
