### ISSUE TITLE
Questions: is it possible to fatpack plack ?

### ISSUE THREAD

**Issue by empierre** [plack/Plack#532]
Hello,

  I plan to make a synology package but the barebone perl and multiple processors structure needs to understand what and how to do it. 

   I wanted to go with Dancer2 for it is pure perl, but I still need plack.

  I've not yet managed to make it run with FatPack, is that possible ? Also what way would you recommend me to deploy such dependencies without local compilation ? (no compiler by default on synology)

**Comment by miyagawa** [comment]
Yes, Plack has no hard XS dependencies, and should be able to fatpack.
