### ISSUE TITLE
Compatability with HTTP::Headers broken

### ISSUE THREAD

**Issue by zebardy** [plack/Plack#541]
https://github.com/plack/Plack/commit/54c0e25d7f3f55c348afdc3d25274cc48830bbaa breaks compatibility with HTTP::Headers. Which if it is a choice to no longer support HTTP::Headers, but insist upon HTTP::Headers::Fast should probably be documented.

**Comment by miyagawa** [comment]
@kazeburo i think this needs to be fixed.

**Comment by kazeburo** [comment]
Oh. I had missed that the httpheaders has a flatten.
I'll send PR to HTTP::Headers::Fast for adding document about incompatibility.

**Comment by miyagawa** [comment]
Wow, i thought you were substituting the HTTP::Headers flatten method and makes a faster implementation. I think it's better to keep the compatibilities since people expect `$req->headers` works like HTTP::Headers, except that its faster.

**Comment by kazeburo** [comment]
HTTP::Headers::Fast's flatten does escape control characters. HTTP::Headers'one just return keys and values.

It's required 4 steps to fix comatibility I think.
1) Release HTTP::Headers::Fast that rename flatten to other name for example psgi_flatte. Also make flatten as alias to psgi_flatten
2) Release Plack that requires newer HTTP::Headers::Fast and uses psgi_flatten instead of flatten
3) Release HTTP::Headers::Fast that will have flatten compatible with HTTP::Headers
4) Release Plack that requires  HTTP::Headers::Fast released step 3

**Comment by kazeburo** [comment]
another idea.

When HTTP::Headers::Fast's flatten is called in array context, it returns key-value list compatible with HTTP::Headers. 
When flatten is called in scalar context, it returns array-reference contains escaped value.

**Comment by miyagawa** [comment]
which method Plack::Response calls is an implementation detail, and what matters to developers is just `flatten()` method is not compatible, regardless of used inside Plack context or outside. So I'd recommend adding a different method for Plack::Response use, and keep the flatten() implementation compatible.

**Comment by zebardy** [comment]
So it sounds like the plan is to make HTTP:Headers::Fast behave like HTTP::Headers, but keep Plack::Response incompatible with HTTP::Headers?

In order to make Plack::Response able to use HTTP::Headers wouldn't it require putting back the control character escape code for use with HTTP::Headers, then special casing HTTP::Headers::Fast to use it's own code instead? Does this not result in the same code in 2 places and unnecessary complexity?

**Comment by miyagawa** [comment]
@zebardy Plack::Response doesn't use HTTP::Headers anymore, so there's no need to keep the compatibility for it. Which use case are you worried about?

**Comment by zebardy** [comment]
The reason I noticed this issue was that our code started breaking. We needed to convert an internal representation of a response that used HTTP::Headers into a plack response for returning by the plack app. I'll take a look and see if I can describe it better. 

After working out what was going on my work around was to convert any HTTP::Headers objects to HTTP::Headers::Fast objects before converting. 

I don't think it is an unreasonable decision to chose to only support HTTP::Headers::Fast, if that is a conscious choice. However it should probably be documented as such, and this discussion should help anyone else that might get caught out understand what is going on and why.

**Comment by miyagawa** [comment]
There's a doc for setting headers:

```
=item headers

  $headers = $res->headers;
  $res->headers([ 'Content-Type' => 'text/html' ]);
  $res->headers({ 'Content-Type' => 'text/html' });
  $res->headers( HTTP::Headers::Fast->new );

... Setter can take either an array ref, a hash ref or L<HTTP::Headers::Fast> 
object containing a list of headers.
```

So it is already documented.

Granted, this was previously stating "HTTP::Headers" instead, so you might be setting the object directly? That makes sense that this code starts breaking and we shouldn't let that happen.

**Comment by zebardy** [comment]
Actually it seems we were calling 

    return Plack::Response->new(
        $status,
        $headers,
        $body
    );

Admittedly this code was probably written a few years ago.

**Comment by miyagawa** [comment]
And `$headers` is an HTTP::Header object, not an array ref, correct?

**Comment by zebardy** [comment]
In some circumstances, yes.

**Comment by zebardy** [comment]
Our solution was to ensure that `$headers` is now always a HTTP::Headers::Fast object.

**Comment by miyagawa** [comment]
I just released 1.0039 that reverts the change. Thanks for your report and sorry about the regression.

@kazeburo we should make sure HTTP::Headers object should be allowed, because historically we allowed these objects to be set.

**Comment by kazeburo** [comment]
Thanks for reverting and releasing.

I'll send PR to HTTP::Headers::Fast that renames faltten to other name and adds a compatible flatten.

**Comment by miyagawa** [comment]
OK i was sidetracked about a while but I consider this being closed. Let me know if that's not the case.
