### ISSUE TITLE
tests fail on darwin 5.23.6

### ISSUE THREAD

**Issue by karenetheridge** [plack/Plack#543]
as in the cpantesters report that has been submitted under my name:

```
Configuring Plack-1.0039
...
#   Failed test at t/Plack-Middleware/log4perl.t line 38.
#                   ''
#     doesn't match '(?^:INFO - This is info)'
# Looks like you failed 1 test of 2.
t/Plack-Middleware/log4perl.t ........................ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
```

**Comment by miyagawa** [comment]
It would be useful if you link to the report directly.

Is Log::Log4perl up to date? If not, does updating it solve the issue?

**Comment by karenetheridge** [comment]
> It would be useful if you link to the report directly.

I can't; it was just sent :)

Everything is up to date; this is a brand new 5.23.6 install (which was just released today).

**Comment by miyagawa** [comment]
Are you saying it is specific to 5.23.6?

**Comment by eserte** [comment]
This can be reproduced with parallel testing (i.e. using HARNESS_OPTIONS=j4 or so). log4perl.t and log4perl-category.t probably share the same hardcoded temporary file. See also http://www.cpantesters.org/cpan/report/5914459a-a4c7-11e5-b0d8-f74caa3802c5 for another test report.

**Comment by miyagawa** [comment]
Thanks for the report! Now waiting for a patch to come in :)
