### ISSUE TITLE
Dead link at 'see also'

### ISSUE THREAD

**Issue by KES777** [plack/Plack#546]
At [this](http://search.cpan.org/dist/Plack/lib/Plack/MIME.pm) module

this [Rack::Mime](http://search.cpan.org/perldoc?Rack%3A%3AMime) is dead

**Comment by miyagawa** [comment]
It is not dead it is just CPAN pod renderer linking to internal link.

**Comment by KES777** [comment]
and where it can be found?

**Comment by miyagawa** [comment]
it's fixed in master.

**Comment by KES777** [comment]
ok, thank you.
