### ISSUE TITLE
test.suggests could include Log::Dispatch

### ISSUE THREAD

**Issue by kentfredric** [plack/Plack#554]
```
t/Plack-Middleware/lint_utf8_false_alarm.t ........... ok               
t/Plack-Middleware/log_dispatch.t .................... skipped: Test requires module 'Log::Dispatch' but it's not found
t/Plack-Middleware/order.t ........................... ok               
```

**Comment by kentfredric** [comment]
Hrm, exposes other missing deps too.

t/Plack-Middleware/log_dispatch.t .................... skipped: Test requires module 'Log::Dispatch::Array' but it's not found

**Comment by miyagawa** [comment]
I honestly don't really care about these, it's not just "suggests" for tests these are modules used by the middleware itself.

**Comment by kentfredric** [comment]
Yeah, they're not incredibly important, but seeing they're interop tests, it would be useful to encourage /some/ audience ( though not necessarily end users ) to run them.

**Comment by kentfredric** [comment]
( And it would be good for CPAN testers to try test these proactively, so that any bugs that occur don't cause install failures for end users who happen to have the requisite dependencies installed =) )

**Comment by miyagawa** [comment]
Fixed in cab4a4b

**Comment by miyagawa** [comment]
#555 is a separate problem that has been fixed already. 

My Travis CI setup installs all of these suggests modules, and log4perl and log_dispatch tests have been tested for a long time: https://github.com/plack/Plack/blob/master/.travis.yml#L15
https://travis-ci.org/plack/Plack/jobs/117136944

**Comment by kentfredric** [comment]
That's awesome =). But the heterogenity of CPAN testers is good at finding bugs where travis does not.

So while I wouldn't *mandate* such a strategy, I do encourage its use where possible.

**Comment by kentfredric** [comment]
( I'm hoping one day we can have explicit dep phases for "test.author.requires" and friends for similar reasons, the most obvious application being "test.smoke.requires" )
