### ISSUE TITLE
Gazelle, Starman and Starlet tests suites fail against 1.0041 release

### ISSUE THREAD

**Issue by veryrusty** [plack/Plack#571]
The test suites for Gazelle, Starman and Starlet fail against the Plack 1.0041 release.

Gist with the cpanm build log for Gazelle:  https://gist.github.com/veryrusty/5085e870513df8657d2b3176eef28c10

Reverting commit 8ee156b (against current master) is sufficient for those servers to pass their test suites. Haven't attempted to debug further.

**Comment by kazeburo** [comment]
I Think it's required to revert https://github.com/plack/Plack/commit/8ee156b1ec252ff49374bdc1c1fdb71ab56853bf
All Plack::Handler except that PR's Handler::PSGI do not support listen_sock option.

**Comment by miyagawa** [comment]
Reverted in be10ee4

**Comment by veryrusty** [comment]
Thanks @kazeburo, @miyagawa  for the quick follow up!

**Comment by miyagawa** [comment]
This broke one test, though:

```
t/HTTP-Server-PSGI/harakiri.t ........................ 1/? 
#   Failed test at t/HTTP-Server-PSGI/harakiri.t line 35.

#   Failed test at t/HTTP-Server-PSGI/harakiri.t line 36.
#          got: '500'
#     expected: '200'

#   Failed test at t/HTTP-Server-PSGI/harakiri.t line 37.
#          got: 'read timeout at /Users/miyagawa/.plenv/versions/5.20.1/lib/perl5/site_perl/5.20.1/Net/HTTP/Methods.pm line 271.
# '
#     expected: 'Hi'
t/HTTP-Server-PSGI/harakiri.t ........................ 4/? 
#   Failed test at t/HTTP-Server-PSGI/harakiri.t line 40.

#   Failed test at t/HTTP-Server-PSGI/harakiri.t line 41.
#          got: '500'
#     expected: '200'
t/HTTP-Server-PSGI/harakiri.t ........................ 6/? # Looks like you failed 5 tests of 6.
t/HTTP-Server-PSGI/harakiri.t ........................ Dubious, test returned 5 (wstat 1280, 0x500)
Failed 5/6 subtests 
```

**Comment by miyagawa** [comment]
fixed in master.
