### ISSUE TITLE
Plack-1.0042 failed test on NetBSD

### ISSUE THREAD

**Issue by wenheping** [plack/Plack#572]
The error message is :

...
t/Plack-Request/content.t ............................ ok
t/Plack-Request/cookie.t ............................. 1/?
#   Failed test at t/Plack-Request/cookie.t line 16.
#          got: '"spaced out"'
#     expected: 'spaced out'

#   Failed test at t/Plack-Request/cookie.t line 18.
#          got: '""internal quotes""'
#     expected: '"internal quotes"'

#   Failed test at t/Plack-Request/cookie.t line 19.
#          got: '""'
#     expected: ''
# Looks like you failed 3 tests of 15.
t/Plack-Request/cookie.t ............................. Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/15 subtests
t/Plack-Request/double_port.t ........................ ok
t/Plack-Request/hostname.t ........................... ok
..

**Comment by syohex** [comment]
I cannot reproduce on NetBSD 7.0.0 with Perl 5.22.1. Test log is here.

https://gist.github.com/syohex/b3abc0f4995e81cd5820bdaf994ffc40

**Comment by miyagawa** [comment]
You're either running the test suite against an old version of Plack, or you have an outdated Cookie::Baker. Run the test using a proper CPAN client.

**Comment by wenheping** [comment]
Yes, it is caused by outdated Cookie::Baker.
Thank you !

wen
