### ISSUE TITLE
Plack::Response early validations

### ISSUE THREAD

**Issue by ylavoie** [plack/Plack#574]
Current implementation validate late instead of early.
Doing so makes it difficult to find errors when they are produced. I wonder if  new could validate provided elements. status, for instance.

**Comment by miyagawa** [comment]
Show me the example code to illustrate the problem.

**Comment by ylavoie** [comment]
1- A routine fails to comply with PSGI and doesn't initialize a status variable which is then used to set a new Plack::Response
2- The response is passed along a routing path, adjusting only body
3- At the end of the path, the response is finalized and error is triggered, pointing away from the real problem.

**Comment by miyagawa** [comment]
Show me the code, please.
