### ISSUE TITLE
Plack 1.0042 indirectly requires File::Slurp

### ISSUE THREAD

**Issue by 1nickt** [plack/Plack#576]
Hello,

I noticed that when I installed `Plack v1.0042` into a clean lib dir, it indirectly required and installed `File::Slurp`, [which is broken](https://rt.cpan.org/Public/Dist/Display.html?Name=File-Slurp) and should not be used.

The dependency chain is:

`File::Slurp < Test::Name::FromLine < Test::Time < Cookie::Baker < Plack`

Thank you for Plack !

**Comment by miyagawa** [comment]
File a bug for whatever appropriate dist, not here.

I'm sure it uses it for testing purpose and I don't see a problem with this.
