### ISSUE TITLE
Cant name tests?

### ISSUE THREAD

**Issue by djzort** [plack/Plack#593]
Hopefully this hasnt been asked a million times before. But its a kind of a bummer that Test::Plack cant emit test names.

For example:
`test_psgi $app, sub {}, 'My test name';`

or
`test_psgi app => $app, client => $client, name => 'My test name';`

**Comment by haarg** [comment]
`test_psgi` on its own doesn't emit any test results.  It doesn't have any interaction with Test::More or any other test framework.  I don't there's anything appropriate for it to do with a test name.
