### ISSUE TITLE
CLI arguments in Plack::Builder

### ISSUE THREAD

**Issue by djzort** [plack/Plack#597]
Hello,

The plackup documentation instructs that unrecognized cli arguments are passed inwards, however I am trying to determine how they can be recieved by my application which is being mounted with Plack::Builder via a .psgi file

ie.

`plackup --app myapp.psgi --arg1 foo --arg2 bar`

```
use Plack::Builder;
builder {
    mount "/foo" => sub { ... };

```

^ how does sub {} get access to arg1 and arg2? @ARGV is empty

**Comment by miyagawa** [comment]
There is no way to do it and it is by design to make your app less platform dependent. Use environment variables.
