### ISSUE TITLE
Plack::Handler::CGI error from command line

### ISSUE THREAD

**Issue by msmcgillis** [plack/Plack#598]
Simple example script for Plack CGI (test.cgi).

```
#!/usr/bin/perl

use strict;
use warnings;

use Plack::Handler::CGI;

my $app = sub {
  return [ 200, ['Content-Type','text/html' ], [ 42 ]];
};
Plack::Handler::CGI->new->run($app);
```

Generates following error:

```
$ ./test.cgi
Use of uninitialized value in string eq at /usr/share/perl5/vendor_perl/Plack/Handler/CGI.pm line 113.
Status: 200 OK
Content-Type: text/html

42
```

Not sure how compatible the Plack::Handler::CGI is suppose to be with perl CGI but if I use say this CGI (x.cgi):

```
#!/usr/bin/perl

use CGI;

my $cgi=CGI->new;

print $cgi->header;
print $cgi->param("a");
```

Then do something like:

```
$ ./x.cgi a=hello
Content-Type: text/html; charset=ISO-8859-1

hello
```

However if I do what I think might be similar with Plack::Handler::CGI (test2.cgi):

```
#!/usr/bin/perl

use strict;
use warnings;

use Plack::Handler::CGI;
use Plack::Request;

my $app = sub {
  my $env = shift;

  my $req = Plack::Request->new($env);

  return [ 200, ['Content-Type','text/html' ], [ $req->param("a") ]];
};
Plack::Handler::CGI->new->run($app);
```

Then try:
```
$ ./test2.cgi a=hello
Use of uninitialized value in string eq at /usr/share/perl5/vendor_perl/Plack/Handler/CGI.pm line 113.
Status: 200 OK
Content-Type: text/html

```

Not sure if command line usage cases are meant to be supported by Plack::Handler::CGI, if not you can ignore and close but if you want the above to behave like perl CGI then the above are test cases to work into regressions testing. CGI also supports other command line usage options that can be useful in different situations. See: http://perldoc.perl.org/CGI.html#DEBUGGING for more details.

The very simple initial test case might be nice to run without errors even if Plack::Handler::CGI is not meant to or intended to support command line use.

**Comment by miyagawa** [comment]
That message is a warning, not an error, because mandatory environment variables in CGI environment is not setup properly in the shell.

The command line argument (a=hello) use case is a feature in CGI.pm, and is not CGI environment per se defined in RFC3875. Programs using Plack::Handler::CGI is indeed supposed to be invoked from CGI runner, such as Apache's mod_cgi module.
