### ISSUE TITLE
Why is the method set/changed to GET?

### ISSUE THREAD

**Issue by drebolo** [plack/Plack#621]
https://github.com/plack/Plack/blob/9bd556cb28a583862f0bd61c385705ac794c7345/lib/Plack/Middleware/Recursive.pm#L57

**Comment by miyagawa** [comment]
The code is a port of https://github.com/rack/rack/blob/master/lib/rack/recursive.rb and the switch to GET is done there originally. Since this is something like SSI/ESI i think it's reasonable to only limit the behavior to GET (read) access.
