### ISSUE TITLE
Plack::Request->content_type vs. ->headers->content_type

### ISSUE THREAD

**Issue by tsibley** [plack/Plack#624]
Commit 8dcc4e4 (“micro optimization: use raw access for CONTENT_LENGTH and CONTENT_TYPE”) changed `->content_type` and `->content_length` from being shortcuts for the same methods on the `->headers` object to using the raw header value. The documentation still says they're shortcuts, which is no longer true.

This is especially noticeable for `->content_type` since the HTTP::Headers API documents it as returning _just_ the MIME type, without any attributes like charset.  Since the commit above, `->content_type` and `->headers->content_type` now return different values when the request header includes a charset.

At the very least, the documentation and code should match, which means one or the other needs to change.  I'd argue that the code should be reverted since I think the previous behaviour of the methods being shortcuts for the `->headers` API is more useful, but that ship may have sailed.

**Comment by miyagawa** [comment]
Well yes this was changed 8 years ago and i agree that the doc is not correct anymore.

If it were changed recently I would revert and then add a new `raw_content_type` method, but am not sure anymore. There might be some code expecting `content_type` to return the raw value.

**Comment by tsibley** [comment]
Yeah, that was my thought as well.  How about we change the doc to indicate that those methods return the raw value and point folks to `->headers->content_type` if they want a parsed value?

**Comment by tsibley** [comment]
Proposed patch: https://github.com/plack/Plack/pull/625
