### ISSUE TITLE
How to Find Out What Environment (development/production) is Plack running under?

### ISSUE THREAD

**Issue by mikkoi** [plack/Plack#645]
Is there any way to find out which environment Plack is using in a Middleware or inside an app (inside .psgi file)?
I run plackup and I have the same application running in development, staging and production.

**Comment by skaji** [comment]
You may refer to `$ENV{PLACK_ENV}`.
https://metacpan.org/pod/distribution/Plack/script/plackup#-E,-env,-the-PLACK_ENV-environment-variable.

**Comment by mikkoi** [comment]
Thanks. Closing issue.
