### ISSUE TITLE
Move MSIE fixes into separate middleware?

### ISSUE THREAD

**Issue by robrwo** [plack/Plack#666]
The ConditionalGET middleware has a workaround for malformed Internet Explorer headers, from 2009.

Internet Explorer is no longer supported my Microsoft on many of their web servers, and is due to be abandoned by August-October 2021. Many web frameworks and web sites are dropping support for Internet Explorer.

It might be worth removing any IE-specific workarounds, and instead moving them into separate middleware that rewrites requests/responses for Internet Explorer.  (The middleware could be released as a separate distribution as well.)

**Comment by robrwo** [comment]
Likewises, the IIS-fix middleware could also be moved to separate distributions since they address versions of IIS from before 2009.

**Comment by haarg** [comment]
I don't see how ConditionalGET is related to IE at all.

**Comment by robrwo** [comment]
> I don't see how ConditionalGET is related to IE at all.

Like 58 of the version on CPAN 1.0048:
```perl
sub _value {
    my $str = shift;
    # IE sends wrong formatted value(i.e. "Thu, 03 Dec 2009 01:46:32 GMT; length=17936")
    $str =~ s/;.*$//;
    return $str;
}
```

**Comment by robrwo** [comment]
> To my eyes that code is more of a defense in depth against broken clients in general

How many clients in use besides old versions of IE have *that* problem?

I see it as running code that is no longer necessary.  The advantage is that it reduces the the amount of code run, and disadvantage (for the very small number of clients) is that they receive the full response instead of the 304 with no body.

**Comment by miyagawa** [comment]
The syntax of `If-Modified-Since` doesn't allow `;` so what I see it as doing is to strip the invalid tokens from the value before doing the comparison, rather than special-casing IE. I believe you're right that nobody would complain if it didn't exist from the start, but to me that's the robustness principle of "be conservative in what you do, be liberal in what you accept."

**Comment by robrwo** [comment]
No problems, then.
