### ISSUE TITLE
Plack 1.0052-TRIAL?

### ISSUE THREAD

**Issue by robrwo** [plack/Plack#713]
MetaCPAN shows a new version of Plack at https://metacpan.org/release/CRABAPP/Plack-1.0052-TRIAL from a different author. There's nothing in this repo with those changes as far as I can tell.

The diff between them is at [Plack.diff](https://github.com/user-attachments/files/17201509/Plack.diff.txt)

**Comment by miyagawa** [comment]
anyone can upload unauthorized releases to PAUSE and MetaCPAN happily shows it as unauthorized. I know some people (ab)use it to pin releases with Carmel and Carton.

**Comment by robrwo** [comment]
When I look at it on MetaCPAN, I only see it as red and marked as a "developer release" not as unauthorised. 

![Screenshot 2024-10-01 at 22-37-56 Plack-1 0052-TRIAL - Perl Superglue for Web frameworks and Web Servers (PSGI toolkit) - metacpan org](https://github.com/user-attachments/assets/616e92cd-f8b5-443a-aba8-dd36a3943cea)

That is a MetaCPAN issue, though.

However MetaCPAN has been a bit wobbly and not working the past few days. There's also been supply-side attacks on other software recently (xz compression), so I thought it prudent to post a question about it here.

Thanks.

**Comment by miyagawa** [comment]
I suspect PAUSE differentiate unauthorized vs development releases. If you have `-TRIAL` in your distribution name, I guess PAUSE will not even try to index it so the permission check wouldn't be performed. If they upload Plack-1.0052 (without `-TRIAL` suffix) then it would become an unauthorized release.
